// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoterAPI.Data;

#nullable disable

namespace VoterAPI.Migrations
{
    [DbContext(typeof(VoterDbContext))]
    [Migration("20260208155845_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("VoterAPI.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuggestionsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVotingOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxVotes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireApproval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VotingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Boards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vote on which features you'd like to see in our next release",
                            IsClosed = false,
                            IsSuggestionsOpen = true,
                            IsVotingOpen = true,
                            MaxVotes = 3,
                            RequireApproval = false,
                            Title = "Product Features",
                            VotingType = "Multiple"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suggest and vote on office improvement ideas",
                            IsClosed = false,
                            IsSuggestionsOpen = true,
                            IsVotingOpen = true,
                            RequireApproval = true,
                            Title = "Office Improvements",
                            VotingType = "Single"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByUserId = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "What should we do for our next team event?",
                            IsClosed = false,
                            IsSuggestionsOpen = false,
                            IsVotingOpen = true,
                            RequireApproval = false,
                            Title = "Team Event Ideas",
                            VotingType = "Single"
                        });
                });

            modelBuilder.Entity("VoterAPI.Models.Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("VoterAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$cqYR9g2uzVdlt0j0txokSeLbACCohBswHulHjeEDpLcff086G.NOK",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("VoterAPI.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuggestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VotedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SuggestionId", "UserId")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("VoterAPI.Models.Board", b =>
                {
                    b.HasOne("VoterAPI.Models.User", "CreatedBy")
                        .WithMany("Boards")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("VoterAPI.Models.Suggestion", b =>
                {
                    b.HasOne("VoterAPI.Models.Board", "Board")
                        .WithMany("Suggestions")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoterAPI.Models.User", "SubmittedBy")
                        .WithMany("Suggestions")
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("VoterAPI.Models.Vote", b =>
                {
                    b.HasOne("VoterAPI.Models.Suggestion", "Suggestion")
                        .WithMany("Votes")
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoterAPI.Models.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suggestion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VoterAPI.Models.Board", b =>
                {
                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("VoterAPI.Models.Suggestion", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("VoterAPI.Models.User", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Suggestions");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
